# Generated by Django 4.2.2 on 2023-06-30 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='article title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/articles/', verbose_name='image of article')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField()),
                ('categories', models.ManyToManyField(to='blog.category', verbose_name='categories')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
